[package]
name = "gping"
version = "0.1.0"
authors = ["Tom Forbes <tom@tomforb.es>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pinger = "0.1.3"
structopt = "0.3.20"
tui = { version = "0.12.0", features = ["crossterm"] }
# tui uses crossterm 0.17.7
crossterm = "0.17.7"
anyhow = "1.0.34"
histogram = "0.6.9"

[profile.release]
lto = true
