[package]
name = "gping"
version = "0.1.4"
authors = ["Tom Forbes <tom@tomforb.es>"]
edition = "2018"
repository = "https://github.com/orf/gping"
license = "MIT"
description = "Ping, but with a graph."

[dependencies]
pinger = "0.1.5"
structopt = "0.3.20"
tui = { version = "0.12.0", features = ["crossterm"], default_features = false }
# tui uses crossterm 0.17.7
crossterm = "0.17.7"
anyhow = "1.0.34"
histogram = "0.6.9"

[profile.release]
lto = true
