name: gping
version: git
summary: Ping, but with a graphj
description: |
  gping gives ping a nice graph in your terminal.

grade: devel
confinement: devmode

apps:
  gping:
    command: env LC_ALL=C.UTF-8 gping
    plugs: [network]

parts:
  gping:
    plugin: python
    python-version: python3
    source: .
