name: gping
version: git
summary: Ping, but with a graph
description: |
  gping gives ping a nice graph in your terminal.

grade: stable
confinement: strict

apps:
  gping:
    command: env LC_ALL=C.UTF-8 gping
    plugs: [network, network-observe]

parts:
  gping:
    plugin: python
    python-version: python3
    source: .
    source-depth: 1
