on:
  push:
    tags:
      - 'v*'
      - '!v*-post'

jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - uses: mislav/bump-homebrew-formula-action@v1
        with:
          formula-name: gping
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
